import type {
  ExchangeProduct, ExchangeCategory, RedemptionRecord, CSRPartner,
  NearbyOffer, DailyDeal, HeroBanner, ExchangeStats,
} from '@/types/exchange'

export const HERO_BANNERS: HeroBanner[] = [
  {
    id: 'b1',
    emoji: '🌱',
    title: 'Double Redemption Week',
    subtitle: 'Earn 2× value on all Eco Products until Sunday',
    gradient: 'from-emerald-600 to-teal-500',
    badge: 'Limited Offer',
  },
  {
    id: 'b2',
    emoji: '🎁',
    title: 'New Rewards Unlocked',
    subtitle: 'Fresh gift cards & local merchant deals just dropped',
    gradient: 'from-violet-600 to-purple-500',
    badge: 'New Arrivals',
  },
  {
    id: 'b3',
    emoji: '🔥',
    title: 'Flash Sale — 48 Hours Only',
    subtitle: 'Top rewards at up to 60% fewer Impact Credits',
    gradient: 'from-orange-500 to-rose-500',
    badge: 'Flash Sale',
  },
  {
    id: 'b4',
    emoji: '🏆',
    title: 'Top Picks of the Month',
    subtitle: 'Curated by impact leaders in your community',
    gradient: 'from-amber-500 to-yellow-400',
    badge: 'Editor\'s Choice',
  },
]

export const EXCHANGE_PRODUCTS: ExchangeProduct[] = [
  {
    id: 'p1',
    name: 'Café Coffee Day ₹200 Gift Card',
    description: 'Enjoy a hot cup of your favourite brew at any Café Coffee Day outlet across India. Valid on all beverages and food items.',
    emoji: '☕',
    bgColor: 'bg-amber-50',
    brandName: 'Café Coffee Day',
    pointsCost: 250,
    realPrice: 200,
    discountPercent: 20,
    category: 'food',
    stock: 48,
    totalStock: 100,
    isSponsored: false,
    isTrending: true,
    isLimited: false,
    isNew: false,
    rating: 4.3,
    reviews: 214,
    deliveryDays: 0,
    tags: ['coffee', 'food', 'cafe', 'beverage'],
    howToRedeem: 'After redemption, show the QR code at any CCD outlet. The cashier will scan it and apply the discount.',
    terms: 'Valid at all Café Coffee Day outlets. Cannot be combined with other offers. Single use only. Valid for 90 days.',
  },
  {
    id: 'p2',
    name: 'Amazon Pay Gift Card ₹500',
    description: 'Shop millions of products on Amazon.in. Use this gift card for groceries, electronics, fashion, and more.',
    emoji: '📦',
    bgColor: 'bg-orange-50',
    brandName: 'Amazon India',
    pointsCost: 620,
    realPrice: 500,
    discountPercent: 15,
    category: 'gift-cards',
    stock: 30,
    totalStock: 50,
    isSponsored: false,
    isTrending: true,
    isLimited: false,
    isNew: false,
    rating: 4.7,
    reviews: 892,
    deliveryDays: 0,
    tags: ['amazon', 'shopping', 'gift card', 'online'],
    howToRedeem: 'Copy the code from your redemption page and apply it at checkout on Amazon.in under "Gift cards & promotional codes".',
    terms: 'Valid on Amazon.in only. Cannot be used for Amazon Prime subscription. Expires 12 months from issue date.',
  },
  {
    id: 'p3',
    name: 'Himalaya Herbals Skincare Kit',
    description: 'Premium ayurvedic skincare with neem face wash, aloe vera gel, and moisturising cream. All natural, cruelty-free.',
    emoji: '🌿',
    bgColor: 'bg-green-50',
    brandName: 'Himalaya',
    pointsCost: 750,
    realPrice: 350,
    discountPercent: 30,
    category: 'eco',
    stock: 22,
    totalStock: 60,
    isSponsored: true,
    sponsorName: 'Tata Trusts',
    isTrending: false,
    isLimited: false,
    isNew: true,
    rating: 4.5,
    reviews: 341,
    deliveryDays: 5,
    tags: ['skincare', 'organic', 'eco', 'ayurvedic', 'herbal'],
    howToRedeem: 'Redeem your IC and we ship the kit to your registered address within 5 business days.',
    terms: 'Delivery to PIN codes serviced by Speed Post. CSR sponsored — partially subsidised by Tata Trusts.',
  },
  {
    id: 'p4',
    name: 'Ola Ride Credits ₹300',
    description: 'Get ₹300 worth of ride credits on Ola. Valid on Ola Micro, Mini, Prime, and Autos.',
    emoji: '🚗',
    bgColor: 'bg-yellow-50',
    brandName: 'Ola',
    pointsCost: 340,
    realPrice: 300,
    discountPercent: 12,
    category: 'travel',
    stock: 75,
    totalStock: 100,
    isSponsored: false,
    isTrending: true,
    isLimited: false,
    isNew: false,
    rating: 4.1,
    reviews: 528,
    deliveryDays: 0,
    tags: ['ola', 'cab', 'ride', 'travel', 'transport'],
    howToRedeem: 'Apply the promo code in the Ola app under "Vouchers & Offers" before booking your ride.',
    terms: 'Valid on Ola app only. Cannot be used for Ola Electric or rentals. Expires 60 days from redemption.',
  },
  {
    id: 'p5',
    name: 'Jio Recharge ₹149',
    description: 'Unlimited calls, 1GB daily data, and 28-day validity on Jio network. Stay connected, stay impactful.',
    emoji: '📱',
    bgColor: 'bg-blue-50',
    brandName: 'Reliance Jio',
    pointsCost: 170,
    realPrice: 149,
    discountPercent: 12,
    category: 'digital',
    stock: 200,
    totalStock: 200,
    isSponsored: false,
    isTrending: false,
    isLimited: false,
    isNew: false,
    rating: 4.2,
    reviews: 1240,
    deliveryDays: 0,
    tags: ['jio', 'recharge', 'mobile', 'data', 'telecom'],
    howToRedeem: 'Enter your Jio number and we will top-up your account automatically within minutes.',
    terms: 'For Jio prepaid numbers only. One recharge per mobile number per month.',
  },
  {
    id: 'p6',
    name: 'BookMyShow — 2 Movie Tickets',
    description: 'Watch any movie at any multiplex in your city — PVR, INOX, Cinepolis, and more. Valid for 2 tickets.',
    emoji: '🎬',
    bgColor: 'bg-red-50',
    brandName: 'BookMyShow',
    pointsCost: 950,
    realPrice: 800,
    discountPercent: 20,
    category: 'events',
    stock: 15,
    totalStock: 40,
    isSponsored: false,
    isTrending: false,
    isLimited: true,
    isNew: true,
    rating: 4.6,
    reviews: 387,
    expiresAt: '2026-07-31',
    deliveryDays: 0,
    tags: ['movies', 'cinema', 'entertainment', 'bookmyshow'],
    howToRedeem: 'Use the code on BookMyShow app or website during ticket checkout. Applicable to any 2 tickets.',
    terms: '2 tickets of equal or lesser value. Booking fees not covered. Valid until July 31 2026.',
  },
  {
    id: 'p7',
    name: 'Swiggy ₹200 Off Coupon',
    description: 'Get ₹200 off on your next Swiggy order above ₹399. Fresh food from top restaurants near you.',
    emoji: '🍕',
    bgColor: 'bg-orange-50',
    brandName: 'Swiggy',
    pointsCost: 230,
    realPrice: 200,
    discountPercent: 18,
    category: 'food',
    stock: 60,
    totalStock: 100,
    isSponsored: false,
    isTrending: true,
    isLimited: false,
    isNew: false,
    rating: 4.4,
    reviews: 672,
    deliveryDays: 0,
    tags: ['swiggy', 'food', 'delivery', 'restaurant', 'coupon'],
    howToRedeem: 'Apply the promo code in the Swiggy app at cart. Discount applies above minimum order value.',
    terms: 'Minimum order ₹399. Valid on Swiggy app only. One per user. Expires 30 days from redemption.',
  },
  {
    id: 'p8',
    name: 'Nykaa ₹500 Beauty Voucher',
    description: 'Shop skincare, makeup, haircare, and more from 2000+ brands on Nykaa. Free shipping on orders above ₹500.',
    emoji: '💄',
    bgColor: 'bg-pink-50',
    brandName: 'Nykaa',
    pointsCost: 580,
    realPrice: 500,
    discountPercent: 14,
    category: 'fashion',
    stock: 35,
    totalStock: 60,
    isSponsored: false,
    isTrending: false,
    isLimited: false,
    isNew: false,
    rating: 4.3,
    reviews: 298,
    deliveryDays: 0,
    tags: ['nykaa', 'beauty', 'skincare', 'makeup', 'fashion'],
    howToRedeem: 'Apply the gift voucher code at Nykaa checkout. Can be split across multiple orders.',
    terms: 'Valid on Nykaa app and website. Cannot be used for subscription plans. Expires 6 months from issue.',
  },
  {
    id: 'p9',
    name: 'Plant a Tree + Certificate',
    description: 'We plant a real tree in your name in a reforestation zone and send you a digital certificate with GPS coordinates.',
    emoji: '🌳',
    bgColor: 'bg-emerald-50',
    brandName: 'GreenYatra',
    pointsCost: 100,
    realPrice: 199,
    discountPercent: 50,
    category: 'eco',
    stock: 500,
    totalStock: 1000,
    isSponsored: true,
    sponsorName: 'Tata Trusts',
    isTrending: true,
    isLimited: false,
    isNew: false,
    rating: 4.9,
    reviews: 1834,
    deliveryDays: 3,
    tags: ['tree', 'eco', 'environment', 'green', 'carbon'],
    howToRedeem: 'Your tree will be planted within 7 days. You\'ll receive a digital certificate with photo and GPS location.',
    terms: 'CSR sponsored by Tata Trusts. Tree planted in verified reforestation zones. Certificate emailed within 48 hours.',
  },
  {
    id: 'p10',
    name: 'Decathlon Sports Voucher ₹500',
    description: 'Get active with ₹500 off at Decathlon. Shop cricket gear, yoga mats, cycles, running shoes, and more.',
    emoji: '🏋️',
    bgColor: 'bg-blue-50',
    brandName: 'Decathlon',
    pointsCost: 580,
    realPrice: 500,
    discountPercent: 14,
    category: 'fitness',
    stock: 28,
    totalStock: 50,
    isSponsored: false,
    isTrending: true,
    isLimited: false,
    isNew: false,
    rating: 4.4,
    reviews: 456,
    deliveryDays: 0,
    tags: ['decathlon', 'sports', 'fitness', 'cricket', 'yoga'],
    howToRedeem: 'Show the QR code at any Decathlon store or apply the code at decathlon.in during checkout.',
    terms: 'Valid on purchases above ₹1000. In-store and online. Not valid on already discounted items.',
  },
  {
    id: 'p11',
    name: "BYJU'S 1-Month Premium",
    description: "Unlock all BYJU'S courses for Class 6–12, JEE, NEET, UPSC, and more. Learn from India's best educators.",
    emoji: '📚',
    bgColor: 'bg-purple-50',
    brandName: "BYJU'S",
    pointsCost: 1400,
    realPrice: 999,
    discountPercent: 40,
    category: 'learning',
    stock: 50,
    totalStock: 100,
    isSponsored: true,
    sponsorName: 'Microsoft India',
    isTrending: true,
    isLimited: false,
    isNew: true,
    rating: 4.5,
    reviews: 2143,
    deliveryDays: 0,
    tags: ["byju's", 'education', 'learning', 'jee', 'neet', 'school'],
    howToRedeem: "Enter the activation code in your BYJU'S account under Subscriptions. Premium unlocks immediately.",
    terms: 'Valid for one account. Cannot be extended or refunded. Co-sponsored by Microsoft India for student empowerment.',
  },
  {
    id: 'p12',
    name: 'Organic Farm Box — Weekly',
    description: 'Fresh, certified organic vegetables from local farms delivered to your door. Supports local farmers directly.',
    emoji: '🥦',
    bgColor: 'bg-lime-50',
    brandName: 'FarmFresh Co.',
    pointsCost: 400,
    realPrice: 350,
    discountPercent: 25,
    category: 'local',
    stock: 20,
    totalStock: 40,
    isSponsored: false,
    isTrending: false,
    isLimited: true,
    isNew: false,
    rating: 4.6,
    reviews: 183,
    deliveryDays: 2,
    tags: ['organic', 'farm', 'vegetables', 'local', 'healthy'],
    howToRedeem: 'Select your delivery slot after redemption. The farm box will be delivered to your address.',
    terms: 'Delivery within 10 km radius of partner farms. Weekday delivery slots only. Single use.',
  },
  {
    id: 'p13',
    name: 'Blood Donation Kit + Certificate',
    description: 'CSR-sponsored donation-drive support kit with nutrition bars, juice, and an official appreciation certificate.',
    emoji: '🩸',
    bgColor: 'bg-red-50',
    brandName: 'Infosys Foundation',
    pointsCost: 80,
    realPrice: 250,
    discountPercent: 68,
    category: 'health',
    stock: 150,
    totalStock: 200,
    isSponsored: true,
    sponsorName: 'Infosys Foundation',
    isTrending: false,
    isLimited: false,
    isNew: false,
    rating: 4.8,
    reviews: 967,
    deliveryDays: 3,
    tags: ['blood donation', 'health', 'csr', 'certificate', 'infosys'],
    howToRedeem: 'Kit shipped to your address after redemption. Show certificate at blood bank for priority service.',
    terms: '100% CSR sponsored by Infosys Foundation. Delivered to all major cities. Certificate issued jointly.',
  },
  {
    id: 'p14',
    name: 'National Tech Summit Pass',
    description: 'Full access to India\'s premier tech conference — keynotes, workshops, networking, and evening gala. Gold+ only.',
    emoji: '🎫',
    bgColor: 'bg-slate-50',
    brandName: 'TechIndia Events',
    pointsCost: 2800,
    realPrice: 4000,
    discountPercent: 55,
    category: 'exclusive',
    stock: 5,
    totalStock: 10,
    isSponsored: true,
    sponsorName: 'Google India',
    isTrending: false,
    isLimited: true,
    isNew: true,
    rating: 4.9,
    reviews: 42,
    expiresAt: '2026-08-15',
    deliveryDays: 3,
    tags: ['conference', 'tech', 'exclusive', 'networking', 'summit'],
    minLevel: 'Gold',
    howToRedeem: 'Verified members receive a physical lanyard pass and digital QR ticket within 3 days of redemption.',
    terms: 'Gold Reward Level or above required. Non-transferable. Valid only for confirmed date. Limited to 5 passes.',
  },
  {
    id: 'p15',
    name: 'MG Road Café — 2 Coffees Free',
    description: 'Enjoy 2 specialty coffees at MG Road Café, a local social impact business employing young adults with disabilities.',
    emoji: '☕',
    bgColor: 'bg-yellow-50',
    brandName: 'MG Road Café',
    pointsCost: 120,
    realPrice: 180,
    discountPercent: 33,
    category: 'local',
    stock: 30,
    totalStock: 50,
    isSponsored: false,
    isTrending: false,
    isLimited: false,
    isNew: false,
    rating: 4.7,
    reviews: 89,
    deliveryDays: 0,
    tags: ['local', 'cafe', 'coffee', 'social enterprise', 'nearby'],
    howToRedeem: 'Show the QR code at MG Road Café counter. Valid for any 2 hot or cold beverages.',
    terms: 'Valid at MG Road Café outlet only. Dine-in only. Not transferable. Valid 60 days from redemption.',
  },
]

export const EXCHANGE_CATEGORIES: ExchangeCategory[] = [
  { id: 'eco',          label: 'Eco Products',   emoji: '🌱', count: 3, bgColor: 'bg-emerald-50' },
  { id: 'electronics',  label: 'Electronics',    emoji: '📱', count: 2, bgColor: 'bg-blue-50'    },
  { id: 'gift-cards',   label: 'Gift Cards',     emoji: '🎁', count: 4, bgColor: 'bg-violet-50'  },
  { id: 'food',         label: 'Food & Dining',  emoji: '🍕', count: 5, bgColor: 'bg-orange-50'  },
  { id: 'travel',       label: 'Travel',         emoji: '✈️', count: 3, bgColor: 'bg-sky-50'     },
  { id: 'health',       label: 'Health',         emoji: '💊', count: 4, bgColor: 'bg-red-50'     },
  { id: 'learning',     label: 'Learning',       emoji: '📚', count: 3, bgColor: 'bg-purple-50'  },
  { id: 'fitness',      label: 'Fitness',        emoji: '💪', count: 3, bgColor: 'bg-lime-50'    },
  { id: 'plants',       label: 'Plants',         emoji: '🌿', count: 2, bgColor: 'bg-green-50'   },
  { id: 'fashion',      label: 'Fashion',        emoji: '👗', count: 3, bgColor: 'bg-pink-50'    },
  { id: 'events',       label: 'Events',         emoji: '🎫', count: 4, bgColor: 'bg-amber-50'   },
  { id: 'digital',      label: 'Digital',        emoji: '💻', count: 5, bgColor: 'bg-indigo-50'  },
  { id: 'donations',    label: 'Donations',      emoji: '❤️', count: 3, bgColor: 'bg-rose-50'    },
  { id: 'local',        label: 'Local Merchants',emoji: '🏪', count: 6, bgColor: 'bg-yellow-50'  },
  { id: 'exclusive',    label: 'Exclusive',      emoji: '👑', count: 2, bgColor: 'bg-slate-50'   },
]

export const DAILY_DEALS: DailyDeal[] = [
  {
    id: 'dd1',
    name: 'Flipkart ₹150 Super Coin Coupon',
    emoji: '🛒',
    bgColor: 'bg-blue-50',
    brandName: 'Flipkart',
    pointsCost: 160,
    realPrice: 150,
    discountPercent: 35,
    endsAt: new Date(Date.now() + 4.5 * 3600 * 1000).toISOString(),
    claimed: 78,
    total: 100,
  },
  {
    id: 'dd2',
    name: "Domino's Buy 1 Get 1 Pizza",
    emoji: '🍕',
    bgColor: 'bg-red-50',
    brandName: "Domino's",
    pointsCost: 280,
    realPrice: 350,
    discountPercent: 50,
    endsAt: new Date(Date.now() + 2.2 * 3600 * 1000).toISOString(),
    claimed: 43,
    total: 50,
  },
]

export const NEARBY_OFFERS: NearbyOffer[] = [
  { id: 'n1', name: 'Chai Point', type: 'Café',            distance: '0.2 km', pointsRequired: 50,  validDays: 3, rating: 4.5, offer: '10% off any chai',       emoji: '🍵' },
  { id: 'n2', name: 'City Books', type: 'Bookstore',       distance: '0.5 km', pointsRequired: 100, validDays: 7, rating: 4.3, offer: '₹50 off on purchase',    emoji: '📖' },
  { id: 'n3', name: 'FreshMart',  type: 'Grocery',         distance: '0.8 km', pointsRequired: 150, validDays: 5, rating: 4.6, offer: 'Free delivery on order', emoji: '🛒' },
  { id: 'n4', name: 'YogaZen',    type: 'Fitness Studio',  distance: '1.1 km', pointsRequired: 200, validDays: 14,rating: 4.8, offer: '1 free yoga class',      emoji: '🧘' },
]

export const REDEMPTION_HISTORY: RedemptionRecord[] = [
  {
    id: 'r1',
    productName: 'Amazon Pay Gift Card ₹500',
    merchantName: 'Amazon India',
    pointsUsed: 620,
    redeemedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    status: 'completed',
    code: 'AMZN-IMP-7X4K',
    emoji: '📦',
  },
  {
    id: 'r2',
    productName: 'Café Coffee Day ₹200 Gift Card',
    merchantName: 'Café Coffee Day',
    pointsUsed: 250,
    redeemedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    status: 'completed',
    code: 'CCD-IMP-3M9P',
    emoji: '☕',
  },
  {
    id: 'r3',
    productName: 'BookMyShow — 2 Movie Tickets',
    merchantName: 'BookMyShow',
    pointsUsed: 950,
    redeemedAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    status: 'expired',
    code: 'BMS-IMP-2V8Q',
    expiresAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    emoji: '🎬',
  },
  {
    id: 'r4',
    productName: 'National Tech Summit Pass',
    merchantName: 'TechIndia Events',
    pointsUsed: 2800,
    redeemedAt: new Date(Date.now() + 5 * 86400000).toISOString(),
    status: 'upcoming',
    code: 'TECH-IMP-9A1Z',
    expiresAt: new Date(Date.now() + 60 * 86400000).toISOString(),
    emoji: '🎫',
  },
]

export const CSR_PARTNERS: CSRPartner[] = [
  { id: 'c1', name: 'Tata Trusts',        initials: 'TT', bgColor: 'bg-blue-600',   campaign: 'Clean Village Initiative',    rewardsSponsored: 58, impactGenerated: '₹2.8L' },
  { id: 'c2', name: 'Infosys Foundation', initials: 'IF', bgColor: 'bg-indigo-600', campaign: 'Digital Health Access',       rewardsSponsored: 41, impactGenerated: '₹1.9L' },
  { id: 'c3', name: 'HCL Foundation',     initials: 'HC', bgColor: 'bg-green-600',  campaign: 'Green Tech Communities',      rewardsSponsored: 32, impactGenerated: '₹1.4L' },
  { id: 'c4', name: 'Microsoft India',    initials: 'MS', bgColor: 'bg-teal-600',   campaign: 'Learning for Every Student',  rewardsSponsored: 47, impactGenerated: '₹2.2L' },
  { id: 'c5', name: 'Google India',       initials: 'GI', bgColor: 'bg-red-500',    campaign: 'Internet Safety & Access',    rewardsSponsored: 36, impactGenerated: '₹1.7L' },
]

export const EXCHANGE_GLOBAL_STATS: ExchangeStats = {
  productsRedeemed: 12450,
  moneySaved: '₹28.5L',
  co2Saved: '1.2 tonnes',
  treesSponsored: 8500,
  csrCampaigns: 23,
}

export const LEADERBOARD_REWARDS: ExchangeProduct[] = [
  {
    id: 'lr1',
    name: 'VIP Event Pass — CM Conclave',
    description: 'Meet elected representatives and top bureaucrats at the Chief Minister\'s Civic Conclave. Invite-only event.',
    emoji: '🏛️',
    bgColor: 'bg-amber-50',
    brandName: 'State Government',
    pointsCost: 5000,
    realPrice: 10000,
    discountPercent: 50,
    category: 'exclusive',
    stock: 3,
    totalStock: 3,
    isSponsored: false,
    isTrending: false,
    isLimited: true,
    isNew: false,
    rating: 5.0,
    reviews: 8,
    tags: ['vip', 'exclusive', 'government', 'conclave'],
    minLevel: 'Platinum',
    howToRedeem: 'Verified by MLA office. Pass issued after identity verification.',
    terms: 'Platinum level only. Non-transferable. Valid for announced date only.',
  },
  {
    id: 'lr2',
    name: 'Scholarship Voucher — ₹10,000',
    description: 'Full scholarship for a 3-month skill development or coding bootcamp at a partner institute.',
    emoji: '🎓',
    bgColor: 'bg-purple-50',
    brandName: 'NSDC Partner',
    pointsCost: 8000,
    realPrice: 10000,
    discountPercent: 20,
    category: 'learning',
    stock: 5,
    totalStock: 5,
    isSponsored: true,
    sponsorName: 'Microsoft India',
    isTrending: false,
    isLimited: true,
    isNew: false,
    rating: 4.9,
    reviews: 14,
    tags: ['scholarship', 'education', 'bootcamp', 'skill'],
    minLevel: 'Gold',
    howToRedeem: 'Enrolment confirmed within 7 days after verification by partner institute.',
    terms: 'Gold level or above. Academic year 2026–27 only. One per user.',
  },
  {
    id: 'lr3',
    name: 'Premium Internship Certificate',
    description: 'A verified 4-week virtual internship at a CSR partner company with a co-signed certificate of excellence.',
    emoji: '💼',
    bgColor: 'bg-slate-50',
    brandName: 'Infosys Foundation',
    pointsCost: 3500,
    realPrice: 5000,
    discountPercent: 30,
    category: 'exclusive',
    stock: 8,
    totalStock: 10,
    isSponsored: true,
    sponsorName: 'Infosys Foundation',
    isTrending: false,
    isLimited: true,
    isNew: true,
    rating: 4.8,
    reviews: 21,
    tags: ['internship', 'career', 'certificate', 'infosys'],
    minLevel: 'Silver',
    howToRedeem: 'Onboarding email with internship schedule sent within 48 hours.',
    terms: 'Silver level or above. Requires 10 hours/week commitment for 4 weeks.',
  },
]
